<?xml version="1.0"?>
<package format="3">
  <name>test_pub_nav_cmd</name>
  <version>0.0.1</version>
  <description>Test build for pub_nav_cmd</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>drdds</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>